@baseAddress = http://localhost:5187

###
POST {{baseAddress}}/api/v1/files
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="hello-world.txt"
Content-Type: text/plain

Hello World
------WebKitFormBoundary--
###
DELETE {{baseAddress}}/api/v1/files
Content-Type: application/json
{
  "fileName": "0ed7592f-dc1e-47fd-a6e9-eeb5583736ef.txt"
}
###