@baseAddress = http://localhost:5292
@categoryId = 08ddfdb4-a49f-13fe-8ce9-eebb46630000

GET {{baseAddress}}/api/categories
Accept: application/json
###

Post {{baseAddress}}/api/categories
Accept: application/json
Content-Type: application/json
{
  "name": "New Category"
}
###

GET {{baseAddress}}/api/categories/{{categoryId}}
Accept: application/json
###

POST {{baseAddress}}/api/courses
Accept: application/json
Content-Type: application/json

{
  "name": "New Course 2",
  "description": "This is a new course",
  "price": 99.99,
  "ImageUrl": "https://example.com/course-image.jpg",
  "categoryId": "{{categoryId}}"
}
###