@baseAddress = http://localhost:5292
@categoryId = 08ddfe67-6c65-671f-8ce9-eebb46630000
@courseId = 08ddfe67-6c91-5460-8ce9-eebb46630000
@userId = 46630000-eebb-8ce9-3bed-08ddfe676c91

GET {{baseAddress}}/api/v1/categories
Accept: application/json
###

Post {{baseAddress}}/api/v1/categories
Accept: application/json
Content-Type: application/json
{
  "name": "New Category"
}
###

GET {{baseAddress}}/api/v1/categories/{{categoryId}}
Accept: application/json
###

POST {{baseAddress}}/api/v1/courses
Accept: application/json
Content-Type: application/json

{
  "name": "New Course 4",
  "description": "This is a new course",
  "price": 99.99,
  "ImageUrl": "https://example.com/course-image.jpg",
  "categoryId": "{{categoryId}}"
}
###

PUT {{baseAddress}}/api/v1/courses
Accept: application/json
Content-Type: application/json

{
  "Id": "{{courseId}}",
  "name": "New Course 22",
  "description": "This is a new course",
  "price": 99.99,
  "ImageUrl": "https://example.com/course-image2.jpg",
  "categoryId": "{{categoryId}}"
}
###


DELETE {{baseAddress}}/api/v1/courses/{{courseId}}
Accept: application/json
###


GET {{baseAddress}}/api/v1/courses
Accept: application/json
###

GET {{baseAddress}}/api/v1/courses/{{courseId}}
Accept: application/json
###

GET {{baseAddress}}/api/v1/courses/user/{{userId}}
Accept: application/json
###
