@baseAddress = http://localhost:5292

GET {{baseAddress}}/api/categories
Accept: application/json
###

Post {{baseAddress}}/api/categories
Accept: application/json
Content-Type: application/json
{
  "name": "New Category"
}
###
